<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9ef97ez\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9ef97ez/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9ef97ez.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9ef97ez\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9ef97ez\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9ef97ez',
    'container.build_id' => '3ace1ee6',
    'container.build_time' => 1585272264,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9ef97ez');
